config/routes.rb
Compress::Application.routes.draw do
  require 'api'
  mount GjbApi::API => '/'
  root 'zip_files#index'

  resources :zip_files

end

app/models/zip_file.rb
# encoding: utf-8
class ZipFile < ActiveRecord::Base

  default_scope  order: 'id desc'

  attr_accessible :name,:file,:download
  mount_uploader :file, FileUploader



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/zip_files_controller.rb
#encoding: utf-8
class ZipFilesController < ApplicationController
  def index
    @zip_files = ZipFile.limit(10)
    respond_to do |format|
      format.html
      format.json { render json: @zip_files }
    end
  end

  def show
    @zip_file = ZipFile.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @zip_file }
    end
  end

  def new
    @zip_file = ZipFile.new
    respond_to do |format|
      format.html
      format.json { render json: @zip_file }
    end
  end

  #def edit
  #  @zip_file = ZipFile.find(params[:id])
  #end

  def create
    @zip_file = ZipFile.new(params[:zip_file])
    respond_to do |format|
      if @zip_file.save
        format.html { redirect_to @zip_file, notice: '上传成功,马上开始无损压缩处理...' }
        format.json { render json: @zip_file }
      else
        format.html { render action: 'new' }
        format.json { render json: @zip_file.errors }
      end
    end
  end

  def destroy
    @zip_file = ZipFile.find(params[:id])
    @zip_file.destroy
    respond_to do |format|
      format.html { redirect_to zip_files_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>批量压缩文件</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zip_files/_form.html.haml
= simple_form_for(@zip_file) do |f|
  = f.error_notification
  %fieldset
    = f.input :name, :label => '名称(可以不填)'
    = f.input :file, :label => '原图zip文件',:as=>:file
    = f.submit '保存' , :class => 'btn btn-primary'

app/views/zip_files/index.html.haml
= link_to '上传压缩文件', new_zip_file_path,:class=>'pjax'
- if @zip_files.present?
  %table.table.table-condensed.table-striped
    %thead
      %tr
        %th.header 序号
        %th.header 时间
        %th.header 名称
        %th.header 原文件地址
        %th.header 压缩后地址
    %tbody
      - @zip_files.each do |zip_file|
        %tr
          %td.string_field= zip_file.id
          %td.string_field= zip_file.created_at
          %td
            - if zip_file.name
              = zip_file.name
          %td
            = link_to '下载', zip_file.file.url
          %td
            - if zip_file.download
              = link_to '下载', zip_file.download

app/views/zip_files/new.html.haml
%h1 麻烦上传zip文件

= render 'form'

= link_to 'Back', zip_files_path

app/views/zip_files/show.html.haml
%table.table.table-condensed.table-striped
  %thead
    %tr
      %th.header 原文件下载地址
      %th.header 压缩后下载地址
      %th
  %tbody
    %tr
      %td
        = link_to '下载', @zip_file.file.url ,:class=>'pjax'
      %td
        - if @zip_file.download
          = link_to '下载', "/#{@zip_file.download}"